app:
  registry:
    address: localhost:2181

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.60.152.234:3306/hundsun?serverTimezone=GMT%2b8
    username: chl
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 6000