app:
  name: gateway
  group: demo
  server:
    port: 8090
  registry:
    address: localhost:2181

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.60.152.234:3306/hundsun?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: chl
    password: 123456