app:
  registry:
    address: localhost:2181

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hundsun?serverTimezone=GMT%2b8
    username: root
    password: 951753.0
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 6000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml