app:
  name: user
  group: demo
  server:
    port: 12222

config:
  location: classpath:middleware.properties

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
